# Generated by Django 2.2 on 2019-04-17 21:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_sold_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('sale_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('active_ingredients', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('units_sold', models.PositiveIntegerField(default=0, editable=False)),
                ('units_left', models.PositiveIntegerField(default=0, editable=False)),
                ('units_sold_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=19)),
                ('units_left_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=19)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shelf.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_sold', models.PositiveIntegerField()),
                ('units_sold_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.GroupSale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.Product')),
            ],
        ),
    ]
