# Generated by Django 2.2.1 on 2020-09-21 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_sold_value', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('sale_count', models.PositiveIntegerField(default=0, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('active_ingredients', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Branch')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(upload_to='upload/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('units_sold', models.PositiveIntegerField(default=0, editable=False)),
                ('units_left', models.PositiveIntegerField(default=0, editable=False)),
                ('units_sold_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=19)),
                ('units_left_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=19)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shelf.Product')),
            ],
            options={
                'ordering': ('product__name',),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_sold', models.PositiveIntegerField()),
                ('units_sold_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('group_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.GroupSale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.Product')),
            ],
        ),
    ]
