# Generated by Django 2.2.1 on 2020-09-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20190505_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsale',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('product__name',)},
        ),
    ]
