# Generated by Django 2.2.1 on 2020-09-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_auto_20200918_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_image', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
